/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppCreateRouteImport } from './routes/app/create'
import { Route as AppVaultIdRouteImport } from './routes/app/vault.$id'
import { Route as AppVaultIdPolicyRouteImport } from './routes/app/vault.$id.policy'
import { Route as AppVaultIdActivityRouteImport } from './routes/app/vault.$id.activity'

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCreateRoute = AppCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVaultIdRoute = AppVaultIdRouteImport.update({
  id: '/vault/$id',
  path: '/vault/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVaultIdPolicyRoute = AppVaultIdPolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => AppVaultIdRoute,
} as any)
const AppVaultIdActivityRoute = AppVaultIdActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppVaultIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/docs': typeof DocsRoute
  '/app/create': typeof AppCreateRoute
  '/app/': typeof AppIndexRoute
  '/app/vault/$id': typeof AppVaultIdRouteWithChildren
  '/app/vault/$id/activity': typeof AppVaultIdActivityRoute
  '/app/vault/$id/policy': typeof AppVaultIdPolicyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/app/create': typeof AppCreateRoute
  '/app': typeof AppIndexRoute
  '/app/vault/$id': typeof AppVaultIdRouteWithChildren
  '/app/vault/$id/activity': typeof AppVaultIdActivityRoute
  '/app/vault/$id/policy': typeof AppVaultIdPolicyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/docs': typeof DocsRoute
  '/app/create': typeof AppCreateRoute
  '/app/': typeof AppIndexRoute
  '/app/vault/$id': typeof AppVaultIdRouteWithChildren
  '/app/vault/$id/activity': typeof AppVaultIdActivityRoute
  '/app/vault/$id/policy': typeof AppVaultIdPolicyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/docs'
    | '/app/create'
    | '/app/'
    | '/app/vault/$id'
    | '/app/vault/$id/activity'
    | '/app/vault/$id/policy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/app/create'
    | '/app'
    | '/app/vault/$id'
    | '/app/vault/$id/activity'
    | '/app/vault/$id/policy'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/docs'
    | '/app/create'
    | '/app/'
    | '/app/vault/$id'
    | '/app/vault/$id/activity'
    | '/app/vault/$id/policy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  DocsRoute: typeof DocsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/create': {
      id: '/app/create'
      path: '/create'
      fullPath: '/app/create'
      preLoaderRoute: typeof AppCreateRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/vault/$id': {
      id: '/app/vault/$id'
      path: '/vault/$id'
      fullPath: '/app/vault/$id'
      preLoaderRoute: typeof AppVaultIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/vault/$id/policy': {
      id: '/app/vault/$id/policy'
      path: '/policy'
      fullPath: '/app/vault/$id/policy'
      preLoaderRoute: typeof AppVaultIdPolicyRouteImport
      parentRoute: typeof AppVaultIdRoute
    }
    '/app/vault/$id/activity': {
      id: '/app/vault/$id/activity'
      path: '/activity'
      fullPath: '/app/vault/$id/activity'
      preLoaderRoute: typeof AppVaultIdActivityRouteImport
      parentRoute: typeof AppVaultIdRoute
    }
  }
}

interface AppVaultIdRouteChildren {
  AppVaultIdActivityRoute: typeof AppVaultIdActivityRoute
  AppVaultIdPolicyRoute: typeof AppVaultIdPolicyRoute
}

const AppVaultIdRouteChildren: AppVaultIdRouteChildren = {
  AppVaultIdActivityRoute: AppVaultIdActivityRoute,
  AppVaultIdPolicyRoute: AppVaultIdPolicyRoute,
}

const AppVaultIdRouteWithChildren = AppVaultIdRoute._addFileChildren(
  AppVaultIdRouteChildren,
)

interface AppRouteRouteChildren {
  AppCreateRoute: typeof AppCreateRoute
  AppIndexRoute: typeof AppIndexRoute
  AppVaultIdRoute: typeof AppVaultIdRouteWithChildren
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppCreateRoute: AppCreateRoute,
  AppIndexRoute: AppIndexRoute,
  AppVaultIdRoute: AppVaultIdRouteWithChildren,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  DocsRoute: DocsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
