[features]
resolution = true
skip-lint = false

[toolchain]
anchor_version = "0.32.1"
[programs.localnet]
krypton_core = "DQVp9hnnU6zbyPCJbcEnS6F1fWZMQ2yCCH9jL6cFVPxF"

[programs.devnet]
krypton_core = "DQVp9hnnU6zbyPCJbcEnS6F1fWZMQ2yCCH9jL6cFVPxF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/chessonchain-casino-deployer.json"

