[features]
resolution = true
skip-lint = false

[toolchain]
anchor_version = "0.32.1"
[programs.localnet]
krypton_core = "7CpwaaPcgxiC2oJv8ZdVX6m7fQZ2qDnQ6hGfUayvq1AS"

[programs.devnet]
krypton_core = "7CpwaaPcgxiC2oJv8ZdVX6m7fQZ2qDnQ6hGfUayvq1AS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/chessonchain-casino-deployer.json"

